theme: "minima"

title: "Elaine Liu"
author: "me"
email: "exliu@mit.edu"
description: "elaine's little basement library"

# minima variables
# twitter_username: "twitteruser"
# github_username: "githubuser"
linkedin_username: elainexliu
#facebook_username: username
#flickr_username: username
instagram_username: elainexliu
#pinterest_username: username
youtube_username: elainexliu

kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  strip_title: true
  collections: true
  
header_pages:
  - projects.md
  - writing.md

collections:
  projects:
    output: true
  
plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: post project
    values:
      tags: other thoughts
      project-type: apps hardware fundamentals