theme: "minima"

title: "Elaine Liu"
author: "me"
email: "exliu@mit.edu"
description: "elaine's little attic library"

# minima variables
# twitter_username: "twitteruser"
# github_username: "githubuser"
linkedin_username: elainexliu
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
youtube_username: elainexliu

# rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true
  
header_pages:
  - projects.html 
  - resume.html
  - archive.md
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
home_post_limit: 3

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
